[package]
name = "shared"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
postcard = { workspace = true }
tokio-vsock = { workspace = true }
tokio = { workspace = true }
